In [1]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}04-01-2020.csv", encoding="utf-8-sig")
doc.head()

,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key
0,45001.0,Abbeville,South Carolina,US,2020-04-01 21:58:49,34.223334,-82.461707,4,0,0,4,"Abbeville, South Carolina, US"
1,22001.0,Acadia,Louisiana,US,2020-04-01 21:58:49,30.295065,-92.414197,47,1,0,46,"Acadia, Louisiana, US"
2,51001.0,Accomack,Virginia,US,2020-04-01 21:58:49,37.767072,-75.632346,7,0,0,7,"Accomack, Virginia, US"
3,16001.0,Ada,Idaho,US,2020-04-01 21:58:49,43.452658,-116.241552,195,3,0,192,"Ada, Idaho, US"
4,19001.0,Adair,Iowa,US,2020-04-01 21:58:49,41.330756,-94.471059,1,0,0,1,"Adair, Iowa, US"

In [2]:
import pandas as pd

PATH = "COVID-19-master/csse_covid_19_data/csse_covid_19_daily_reports/"
doc = pd.read_csv(f"{PATH}03-01-2020.csv", encoding="utf-8-sig")
doc.head()

,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,Latitude,Longitude
0,Hubei,Mainland China,2020-03-01T10:13:19,66907,2761,31536,30.9756,112.2707
1,NaN,South Korea,2020-03-01T23:43:03,3736,17,30,36.0000,128.0000
2,NaN,Italy,2020-03-01T23:23:02,1694,34,83,43.0000,12.0000
3,Guangdong,Mainland China,2020-03-01T14:13:18,1349,7,1016,23.3417,113.4244
4,Henan,Mainland China,2020-03-01T14:13:18,1272,22,1198,33.8820,113.6140

In [7]:
doc = pd.read_csv(f"{PATH}01-22-2020.csv", encoding="utf-8-sig")

# 위 처럼 생긴 값 찾아오고, 없으면 아래 처럼 생긴 값 찾아 와!
try :
    doc = doc[["Province_State", "Country_Region", "Confirmed"]]
except :
    doc = doc[["Province/State", "Country/Region", "Confirmed"]]
    doc.columns = ["Province_State", "Country_Region", "Confirmed"]


doc = doc.dropna(subset=["Confirmed"])
doc = doc.astype({"Confirmed": "int64"})

doc.head()

  Province_State  Country_Region  Confirmed
0          Anhui  Mainland China          1
1        Beijing  Mainland China         14
2      Chongqing  Mainland China          6
3         Fujian  Mainland China          1
5      Guangdong  Mainland China         26